---
title: "Philosopher Net Community Detection"
author: "Matthew Bone"
date: "04/02/2021"
output: 
  html_document:
    fig_height: 3
    fig_width: 5
  pdf_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, setup, include=FALSE}
library(mosaic)   # Load additional packages here 
library(tidyverse)
library(readr)
library(visNetwork)
library(igraph)
library(rpart)
library(ggformula)
library(Hmisc)
library(leaflet)
library(htmlwidgets)
set.seed(1)

source("functions.R")
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
```

```{r, include=FALSE}
toss_list = '(analytic|custom_cnm5|custom_cnm6|custom_cnm7|custom_cnm8|custom_cnm9|custom_cnm10|custom_cnm11|custom_cnm12|custom_cnm13|custom_klb0|custom_cnm0|custom_cnm1|custom_cnm2|custom_cnm3|custom_cnm4|custom_lab1|custom_lab2|custom_lab3|custom_lab4|custom_lab5|custom_lab6|custom_lab7|custom_aflu1|custom_klb0|cnm0|cnm2|cnm3|cnm4|lab1|lab2|lab3|lab4|lab5|lab6|lab7|aflu1|klb0)'

edges <- read_csv("dedges.csv")
nodes <- read_csv("comm_nodes.csv") %>%
  mutate(school = if_else(analytic == 1, 'Analytic', 'Continental'),
         comms = gsub('continental','Actual School',comms),
         comms = gsub(',klb1',',Kernighan-Lin Bisection',comms),
         comms = gsub(',custom_klb1',',Kernighan-Lin Bisection - Custom',comms),
         comms = gsub(',cnm1',',Clauset-Newman-Moore Greedy Algorithm',comms),
         comms = gsub(',custom_cnm1,',',Clauset-Newman-Moore Greedy Algorithm - Custom,',comms),
         comms = gsub(',lab0',',Label Propagation',comms),
         comms = gsub(',custom_lab0',',Label Propagation',comms),
         comms = gsub(',aflu0',',Asynchronous Fluid Community Algorithm',comms),
         comms = gsub(',custom_aflu0',',Asynchronous Fluid Community Algorithm - Custom',comms),
         comms = gsub(toss_list,'',comms),
         comms = gsub(',,*',',', comms),
         comms = gsub(',', '  ', comms),
         comms = str_trim(comms, side = 'both'),
         comms = gsub('  ', ',', comms),
         Community = comms,
         title = paste0("<h3 style='color:Black;font-size:8px;'>", 
                        "<p>", label, "</p>",
                        "<p>School: ", school, "</p>",
                        "<p>Born: ", born, "</p>",
                        "<p>Died: ", died, "</p>",
                        "</h3>"))

nodes
```

```{r}
visNetwork(nodes, edges, width = "100%") %>%
  visPhysics(enabled = T,
             maxVelocity = 15, 
             minVelocity = 10,
             stabilization = list(enabled = T,
                                  iterations = 1000),
             solver = 'forceAtlas2Based',
             adaptiveTimestep = T,
             forceAtlas2Based = list(gravitationalConstant = -300,
                                     avoidOverlap = 1,
                                     springLength = 200,
                                     springConstant = .05,
                                     damping = 1)) %>%
  visEdges(smooth = F, 
           width = .2) %>%
  visNodes(size = 50) %>%
  visGroups(groupname = 'continental', color = 'red')  %>%
  visOptions(selectedBy = list(variable = 'Community', 
                               multiple = T,
                               highlight = T,
                               hideColor = list(background = '#CD5C58',
                                                border = '#DC3C3B')))
  
```

