---
title: "Philosopher Network Visualization"
author: "Matthew Bone"
date: "10/15/20"
output: 
  html_document:
    fig_height: 8
    fig_width: 8
  pdf_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, setup, include=FALSE}
library(mosaic)   # Load additional packages here 
library(tidyverse)
library(readr)
library(visNetwork)
library(igraph)
library(rpart)
library(ggformula)
library(Hmisc)
library(leaflet)
library(htmlwidgets)

source("functions.R")
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
```

```{r, include=FALSE}
edges <- read_csv("edges.csv")

nodes <- read_csv("nodes.csv") %>%
  arrange(born) %>%
  mutate(font.size = 0,
         indegree = indegree(id, edges),
         outdegree = outdegree(id, edges),
         born = as.numeric(substr(born, 1, 4)),
         died = as.numeric(substr(died, 1, 4)),
         born = if_else(!is.na(born) & !is.na(died), 
                        if_else(born > died, -born, born), born),
         died = if_else(born < 0, -died, died),
         level = as.numeric(cut_number(born, 50)),
         value = outdegree,
         color = colorize(indegree),
         title = paste0("<h3 style='color:Black;font-size:8px;'>", 
                        "<p>", label, "</p>",
                        "<p>Born: ", born, "</p>",
                        "<p>Died: ", died, "</p>",
                        "</h3>")) %>%
  filter(!is.na(born) & !(label %in% c('Ibn Hibban', 'Al-Hakim al-Nishapuri')))

nodes[["color"]][is.na(nodes[["color"]])] <- "#00008B"
```

```{r}
n <- colSums(Filter(is.numeric, nodes), na.rm = T)
school <- labels(colSums(Filter(is.numeric, nodes), na.rm = T))

school_count <- data.frame(school, n) %>%
  filter(!(school %in% c('born','died','level','outdegree','value','indegree')))

rownames(school_count) <- c()

top_schools <- school_count %>%
  filter(n > 9)

top_schools %>%
  arrange(-n)

intersect(top_schools$school, school_count$school)
```

```{r, echo=FALSE}
philosophernet <- visNetwork(nodes, edges, width = "100%") %>%
  visPhysics(enabled = T,
             maxVelocity = 10,
             minVelocity = 5,
             timestep = .5,
             hierarchicalRepulsion = list(nodeDistance = 100),
             stabilization = list(iterations = 500)) %>%
  visEdges(smooth = F, 
           arrows = 'to',
           width = .2) %>%
  visHierarchicalLayout(enabled = T, 
                        direction = "LR", 
                        levelSeparation = 50, 
                        sortMethod = "directed",
                        blockShifting = T) %>%
  visOptions(highlightNearest = list(enabled = T, 
                                     algorithm = "hierarchical",
                                     degree = list(from = 0, to = 2)),
             nodesIdSelection = list(enabled = T)) %>%
  visNodes(scaling = list(min = 5, max = 30))
```

```{r}

filter_schools <- function(x) {
  
  paste(intersect(str_split(x, ':')[[1]], top_schools$school), collapse = ',')
  
}



nodes$schools <- lapply(nodes$schools, filter_schools)

View(nodes %>% select(schools))

nodes$schools[5]
str_split(nodes$schools[5], ':')[[1]]
intersect(str_split(nodes$schools[5], ':')[[1]], top_schools$school)
paste(intersect(str_split(nodes$schools[5], ':')[[1]], top_schools$school), collapse = ',')
```

```{r}
visNetwork(nodes, edges, width = "100%") %>%
  visPhysics(enabled = T,
             maxVelocity = 10,
             minVelocity = 5,
             timestep = .5,
             hierarchicalRepulsion = list(nodeDistance = 100),
             stabilization = list(iterations = 500)) %>%
  visEdges(smooth = F, 
           arrows = 'to',
           width = .2) %>%
  visHierarchicalLayout(enabled = T, 
                        direction = "LR", 
                        levelSeparation = 50, 
                        sortMethod = "directed",
                        blockShifting = T) %>%
  visOptions(selectedBy = list(variable = 'schools', multiple = T),
             highlightNearest = F) %>%
  visNodes(scaling = list(min = 5, max = 30))
  
```



```{r}
saveWidget(philosophernet, file = "philosophernet.html")
```

```{r}
philosophernet
```





